// Generated by CoffeeScript 1.6.3
var S, app, createFilterFor, name, _i, _j, _len, _len1, _ref, _ref1,
  __slice = [].slice;

S = require('string');

app = angular.module('string', []);

app.factory('string', function() {
  return S;
});

createFilterFor = function(name, returnsStringObject) {
  var filterName;
  filterName = S("string-" + name).camelize().toString();
  return app.filter(filterName, [
    'string', (function(S) {
      return function() {
        var args, input, out, _ref;
        input = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        out = (_ref = S(input))[name].apply(_ref, args);
        if (returnsStringObject) {
          out = out.toString();
        }
        return out;
      };
    })
  ]);
};

_ref = ['between', 'camelize', 'capitalize', 'chompLeft', 'chompRight', 'collapseWhitespace', 'dasherize', 'decodeHTMLEntities', 'escapeHTML', 'ensureLeft', 'ensureRight', 'humanize', 'left', 'pad', 'padLeft', 'padRight', 'repeat', 'replaceAll', 'right', 'slugify', 'stripPunctuation', 'stripTags', 'times', 'toCSV', 'trim', 'trimLeft', 'trimRight', 'truncate', 'underscore', 'unescapeHTML'];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  name = _ref[_i];
  createFilterFor(name, true);
}

_ref1 = ['contains', 'count', 'endsWith', 'include', 'isAlpha', 'isAlphaNumeric', 'isEmpty', 'isLower', 'isNumeric', 'isUpper', 'lines', 'parseCSV', 'startsWith', 'toBoolean', 'toBool', 'toFloat', 'toInt', 'toInteger'];
for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
  name = _ref1[_j];
  createFilterFor(name, false);
}
